replicaCount: 1
# 각각의 타임스탬프를 독립적으로 관리
backendTimestamp: "20241121004412"
frontendTimestamp: "20241209075820"
backend:
  users:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/backend-users-ecr"
      tag: "20241203034926"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8080
    env:
      USER_SERVER_PORT: "8080"
      USER_JWT_SECRET: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
      USER_SECURITY_USER_NAME: "admin"
      USER_SECURITY_USER_PASSWORD: "1234"
      USER_TOKEN_SECRET_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
      USER_ACCESS_TOKEN_PLUS_HOUR: "1"
      USER_REFRESH_TOKEN_PLUS_HOUR: "24"
    secret:
      USER_DB_URL: "jdbc:mariadb://users-shoppingoo-cicd-db.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/usersdb"
      USER_DB_USERNAME: "shoppingooadmin"
      USER_DB_PASSWORD: "404notfound!"
  brand:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/backend-brand-ecr"
      tag: "20241207193839"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8081
    env:
      BRAND_SERVER_PORT: "8081"
      AWS_REGION: "ap-northeast-2"
      S3_BUCKET_NAME: "shortpingoo-backendbucket"
      BRAND_S3_URL: "https://${S3_BUCKET_NAME}.s3.${AWS_REGION}.amazonaws.com"
    secret:
      BRAND_DB_URL: "jdbc:mariadb://brand-shoppingoo-db-pb.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/branddb?useUnicode=true&characterEncoding=utf8mb4"
      BRAND_DB_USERNAME: "shoppingooadmin"
      BRAND_DB_PASSWORD: "404notfound!"
      FLASK_API_URL: "https://shortpingoo.shop/api/shorts/search"
      AWS_ACCESS_KEY_ID:
        valueFrom:
          secretKeyRef:
            name: shortpingoo-secrets
            key: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        valueFrom:
          secretKeyRef:
            name: shortpingoo-secrets
            key: AWS_SECRET_ACCESS_KEY
  order:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/backend-order-ecr"
      tag: "20241207150326"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8082
    env:
      BRAND_API_URL: https://shortpingoo.shop/api/brand/product/owner
      STOCK_API_URL: https://shortpingoo.shop/open-api/brand/product/stock
    secret:
      ORDER_DB_URL: "jdbc:mariadb://order-shoppingoo-databse-public.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/orderdb?useUnicode=true&characterEncoding=utf8mb4"
      ORDER_DB_USERNAME: "shoppingooadmin"
      ORDER_DB_PASSWORD: "404notfound!"
  apigateway:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/apigateway-ecr"
      tag: "20241207191326"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8089
    env:
      API_GATEWAY_JWT_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
  cart:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/backend-cart-ecr"
      tag: "20241207021236"
      pullPolicy: Always
    service:
      type: ClusterIP
      port: 8084
    secret:
      CART_DB_URL: "jdbc:mariadb://cart-shoppingoo-databse-public.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/cartdb?useUnicode=true&characterEncoding=utf8mb4"
      CART_DB_USERNAME: "shoppingooadmin"
      CART_DB_PASSWORD: "404notfound!"
frontend:
  image:
    repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr"
    tag: "20241209075820"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  env:
    REACT_APP_API_BASE_URL: "https://shortpingoo.shop"
    REACT_APP_API_BASE_URL_APIgateway: "https://shortpingoo.shop"
    REACT_APP_ENV: "production"
ai:
  image:
    repository: "waseoke/ai-sentiment-classification-rds"
    tag: "latest"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 5001
  env:
    FLASK_RUN_HOST: "0.0.0.0"
    FLASK_RUN_PORT: "5001"
    FLASK_APP: "app.py"
  secret:
    YOUTUBE_API_KEY: "AIzaSyASZExETg_UYPJnmjrS0vpw82hI8bqV-n0"
    AI_BRAND_DB_HOST: "brand-shoppingoo-db-pb.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com"
    AI_BRAND_DB_PORT: "3306"
    AI_BRAND_DB_NAME: "branddb"
    AI_BRAND_DB_USER: "shoppingooadmin"
    AI_BRAND_DB_PASSWORD: "404notfound!"
    YOUTUBE_SID: "Ao2CQTYCJ-B0x7gt_"
    YOUTUBE_HSID: "A7Ne40yA7hVZjBOvw"
    YOUTUBE_SSID: "Ao2CQTYCJ-B0x7gt_"
    YOUTUBE_APISID: "7pgVed1atNFG6Pk3/A6Eth5-q1vYjhil5w"
    YOUTUBE_SAPISID: "yzy9eFOWphBx_5nz/Ahdt_c542C-j-ilAs"
    YOUTUBE_LOGIN_INFO: "AFmmF2swRAIgQP2ogF3STnUNxrYvDsT_D4LCrgkcjMefNk3UChPJFvYCIFHasT4V6lmCOJo0fh8lyul4CcgNZe2V1kXiWSn1jGny:QUQ3MjNmempaZWJMcE90dkxqYmNtSkJ0N2ZfQjB0Y2Z6SFdTYmhlMDJtbHJyd21VYVd5ajU1RC14WHJObGU4UXI1b3BCV25NemtVWUNxM3pUd2tIQXllcHlRdl9CMWlWZkdSZGZaSUFwMDVaR2w2aG91XzNCYTYwWTdicG9jdzlGc0RnWGRZOGlZUG83aDZkcUpVZ0JOM2ZuSV9KemVyZl9R"
    YOUTUBE_YSC: "A1n4JrSjKBw"
    YOUTUBE_VISITOR_INFO1_LIVE: "X0lbZcOrEBg"
ingress:
  awsCertArn: "arn:aws:acm:ap-northeast-2:565393064007:certificate/82c4718b-d3ec-4d6b-9233-bfaa647368d2"
  tlsSecretName: "shortpingoo-secrets"
  hostName: "shortpingoo.shop"
