replicaCount: 1
# 각각의 타임스탬프를 독립적으로 관리
backendTimestamp: "latest"
frontendTimestamp: "20241119073924"
backend:
  image:
    repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/backend-users-ecr"
    tag: "latest"
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
  env:
    SERVER_PORT: "8080"
    JWT_SECRET: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
    SECURITY_USER_NAME: "admin"
    SECURITY_USER_PASSWORD: "1234"
    TOKEN_SECRET_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
    ACCESS_TOKEN_PLUS_HOUR: "1"
    REFRESH_TOKEN_PLUS_HOUR: "24"
    secret:
      DB_URL: "jdbc:mariadb://users-shoppingoo-database-cicd.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/usersdb"
      DB_USERNAME: "shoppingooadmin"
      DB_PASSWORD: "404notfound!"
frontend:
  image:
    repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-ecr"
    tag: "20241119073759"
    pullPolicy: Always
  service:
    type: LoadBalancer
    port: 80
  env:
    REACT_APP_API_BASE_URL: "https://shortpingoo.shop"
    REACT_APP_ENV: "production"
eureka:
  enabled: true
  server:
    image:
      repository: "565393064007.dkr.ecr.ap-northeast-2.amazonaws.com/eurekaforkubnernetes"
      tag: "latest"
    service:
      type: ClusterIP
      port: 8088
    ingress:
      enabled: true
      host: eureka.shortpingoo.shop
      certificateArn: "arn:aws:acm:ap-northeast-2:565393064007:certificate/82c4718b-d3ec-4d6b-9233-bfaa647368d2"
  client:
    serviceUrl:
      defaultZone: "http://eureka.shortpingoo.shop/eureka/"
    instance:
      preferIpAddress: true
      leaseRenewalIntervalInSeconds: 10
      leaseExpirationDurationInSeconds: 30
ingress:
  awsCertArn: "arn:aws:acm:ap-northeast-2:565393064007:certificate/82c4718b-d3ec-4d6b-9233-bfaa647368d2"
  tlsSecretName: "shortpingoo-secrets"
  hostName: "shortpingoo.shop"
