# Backend Services
apiVersion: v1
kind: Service
metadata:
  name: shortpingoo-backend-brand-svc
  namespace: shortpingoo
spec:
  type: {{ .Values.backend.brand.service.type }}
  selector:
    app: backend-brand
  ports:
    - protocol: TCP
      port: {{ .Values.backend.brand.service.port }}
      targetPort: {{ .Values.backend.brand.service.port }}