# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortpingoo-backend-brand
  namespace: shortpingoo
  labels:
    app: backend-brand
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend-brand
  template:
    metadata:
      labels:
        app: backend-brand
    spec:
      imagePullSecrets:
        - name: regcred  # ECR 인증을 위한 시크릿 이름
      containers:
        - name: backend-brand-container
          image: "{{ .Values.backend.brand.image.repository }}:{{ .Values.backend.brand.image.tag }}"
          imagePullPolicy: {{ .Values.backend.brand.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.brand.service.port }}
          envFrom:
            - configMapRef:
                name: shortpingoo-config
            - secretRef:
                name: shortpingoo-secrets

