# Backend order Services
apiVersion: v1
kind: Service
metadata:
  name: shortpingoo-backend-order-svc
  namespace: shortpingoo
spec:
  type: {{ .Values.backend.order.service.type }}
  selector:
    app: backend-order
  ports:
    - protocol: TCP
      port: {{ .Values.backend.order.service.port }}
      targetPort: {{ .Values.backend.order.service.port }}