apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  # 백엔드 환경 변수
  {{- range .Values.backend.services }}
  {{- if hasKey . "env" }}
  {{- range $key, $value := .env }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}
  {{- end }}

  # 프론트엔드 환경 변수
  REACT_APP_API_BASE_URL: "{{ .Values.frontend.env.REACT_APP_API_BASE_URL }}"
  REACT_APP_ENV: "{{ .Values.frontend.env.REACT_APP_ENV }}"
