apiVersion: v1
kind: ConfigMap
metadata:
  name: shortpingoo-config
data:
  # 백엔드 환경 변수
  # User
  USER_SERVER_PORT: "8080"
  USER_JWT_SECRET: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
  USER_SECURITY_USER_NAME: "admin"
  USER_SECURITY_USER_PASSWORD: "1234"
  USER_TOKEN_SECRET_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
  USER_ACCESS_TOKEN_PLUS_HOUR: "1"
  USER_REFRESH_TOKEN_PLUS_HOUR: "24"
  
  # Brand
  BRAND_SERVER_PORT: "8081"

  # API GATEWAY
  API_GATEWAY_JWT_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"

  # 프론트엔드 환경 변수
  REACT_APP_API_BASE_URL: "https://shortpingoo.shop"
  REACT_APP_API_BASE_URL_APIgateway: "https://shortpingoo.shop"
  REACT_APP_ENV: "production"


  # AI 환경변수
  FLASK_RUN_HOST: "0.0.0.0"
  FLASK_RUN_PORT: "5001"
  FLASK_APP: "app.py"