apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  # 백엔드 환경 변수
  SERVER_PORT: "{{ .Values.backend.env.SERVER_PORT }}"
  JWT_SECRET: "{{ .Values.backend.env.JWT_SECRET }}"
  SECURITY_USER_NAME: "{{ .Values.backend.env.SECURITY_USER_NAME }}"
  SECURITY_USER_PASSWORD: "{{ .Values.backend.env.SECURITY_USER_PASSWORD }}"
  TOKEN_SECRET_KEY: "{{ .Values.backend.env.TOKEN_SECRET_KEY }}"
  ACCESS_TOKEN_PLUS_HOUR: "{{ .Values.backend.env.ACCESS_TOKEN_PLUS_HOUR }}"
  REFRESH_TOKEN_PLUS_HOUR: "{{ .Values.backend.env.REFRESH_TOKEN_PLUS_HOUR }}"

  # 프론트엔드 환경 변수
  REACT_APP_API_BASE_URL: "{{ .Values.frontend.env.REACT_APP_API_BASE_URL }}"
  REACT_APP_ENV: "{{ .Values.frontend.env.REACT_APP_ENV }}"
