apiVersion: v1
kind: ConfigMap
metadata:
  name: shortpingoo-app-config
data:
  # 백엔드 환경 변수
  USER_SERVER_PORT: "8080"
  USER_JWT_SECRET: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
  USER_SECURITY_USER_NAME: "admin"
  USER_SECURITY_USER_PASSWORD: "1234"
  USER_TOKEN_SECRET_KEY: "SpringBootJWTHelperTokenSecretKeyValue123!@1"
  USER_ACCESS_TOKEN_PLUS_HOUR: "1"
  USER_REFRESH_TOKEN_PLUS_HOUR: "24"
  
  BRAND_SERVER_PORT: "8081"
  BRAND_DB_URL: "jdbc:mariadb://brand-shoppingoo-database-cicd.c7s4augo48pb.ap-northeast-2.rds.amazonaws.com:3306/brand-shoppingoo-database-cicd:3306/branddb"
  BRAND_DB_USERNAME: "shoppingooadmin"
  BRAND_DB_PASSWORD: "404notfound!"

  # 프론트엔드 환경 변수
  REACT_APP_API_BASE_URL: "https://shortpingoo.shop"
  REACT_APP_ENV: "production"
