# backend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortpingoo-backend
  labels:
    app: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: regcred  # ECR 인증을 위한 시크릿 이름
      containers:
        - name: backend-container
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.backend.service.port }}
          envFrom:
            - configMapRef:
                name: shortpingoo-config
            - secretRef:
                name: shortpingoo-secrets

---

# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortpingoo-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred  # ECR 인증을 위한 시크릿 이름
      containers:
        - name: frontend-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          envFrom:
            - configMapRef:
                name: shortpingoo-config
            - secretRef:
                name: shortpingoo-secrets