# backend deployment
{{- range .Values.backend.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
  namespace: shortpingoo
  labels:
    app: {{ .name }}
spec:
  replicas: {{ $.Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      imagePullSecrets:
        - name: regcred  # ECR 인증을 위한 시크릿 이름
      containers:
        
        - name: {{ .name }}-container
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            {{- range .ports }}
            - containerPort: {{ .number }}
            {{- end }}
          env:
            {{- if .env }}
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- else }}
            # No environment variables for {{ .name }}
            {{- end }}
            {{- range $key, $value := .secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: shortpingoo-secrets
                  key: {{ $key }}
            {{- end }}
{{- end }}

---

# frontend deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shortpingoo-frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: regcred  # ECR 인증을 위한 시크릿 이름
      containers:
        - name: frontend-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          envFrom:
            - configMapRef:
                name: shortpingoo-config
            - secretRef:
                name: shortpingoo-secrets