# Frontend Services
apiVersion: v1
kind: Service
metadata:
  name: shortpingoo-frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
