apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shortpingoo-app-ingress
  namespace: shortpingoo
  annotations:
    kubernetes.io/ingress.class: "alb"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-northeast-2:565393064007:certificate/82c4718b-d3ec-4d6b-9233-bfaa647368d2"
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-type: "external"
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app.kubernetes.io/instance: shortpingoo-app
spec:
  rules:
    - host: shortpingoo.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shortpingoo-frontend-svc
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: shortpingoo-backend-svc
                port:
                  number: 8080
          - path: /open-api
            pathType: Prefix
            backend:
              service:
                name: shortpingoo-backend-svc
                port:
                  number: 8080

          {{- range .Values.backend.services }}
          {{- $serviceName := .name }}
          {{- range .ports }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}-svc
                port:
                  number: {{ .number }}
          - path: /open-api
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}-svc
                port:
                  number: {{ .number }}
          {{- end }}
          {{- end }}
