apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  USER_DB_URL: "amRiYzptYXJpYWRiOi8vdXNlcnMtc2hvcHBpbmdvby1kYXRhYmFzZS1jaWNkLmM3czRhdWdvNDhwYi5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTozMzA2L3VzZXJzZGI="
  USER_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  USER_DB_PASSWORD: "NDA0bm90Zm91bmQh"
  BRAND_DB_URL: "amRiYzptYXJpYWRiOi8vYnJhbmQtc2hvcHBpbmdvby1kYXRhYmFzZS1jaWNkLmM3czRhdWdvNDhwYi5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTozMzA2L2JyYW5kZGI="
  BRAND_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  BRAND_DB_PASSWORD: "NDA0bm90Zm91bmQh"
  
