apiVersion: v1
kind: Secret
metadata:
  name: shortpingoo-secrets
type: Opaque
data:
  USER_DB_URL: "amRiYzptYXJpYWRiOi8vdXNlcnMtc2hvcHBpbmdvby1jaWNkLWRiLmM3czRhdWdvNDhwYi5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTozMzA2L3VzZXJzZGI="
  USER_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  USER_DB_PASSWORD: "NDA0bm90Zm91bmQh"
  BRAND_DB_URL: "amRiYzptYXJpYWRiOi8vYnJhbmQtc2hvcHBpbmdvby1kYi1wYi5jN3M0YXVnbzQ4cGIuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206MzMwNi9icmFuZGRiP3VzZVVuaWNvZGU9dHJ1ZSZjaGFyYWN0ZXJFbmNvZGluZz11dGY4bWI0"
  BRAND_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  BRAND_DB_PASSWORD: "NDA0bm90Zm91bmQh"

  # BRAND AWS S3 관련 자격 증명
  AWS_ACCESS_KEY_ID: "QUtJQVlISkFOUUJENFhLNlVJTjI="
  AWS_SECRET_ACCESS_KEY: "dDBrWUppbFVpZmV2ODNDSDVwQW9URHNBTTIycWE4ZlNkc1VBaERQNw=="

  # ORDER secret 추가
  ORDER_DB_URL: "amRiYzptYXJpYWRiOi8vb3JkZXItc2hvcHBpbmdvby1kYXRhYnNlLXB1YmxpYy5jN3M0YXVnbzQ4cGIuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb206MzMwNi9vcmRlcmRiP3VzZVVuaWNvZGU9dHJ1ZSZjaGFyYWN0ZXJFbmNvZGluZz11dGY4bWI0"
  ORDER_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  ORDER_DB_PASSWORD: "NDA0bm90Zm91bmQh"

  # CART secret 추가
  CART_DB_URL: "amRiYzptYXJpYWRiOi8vY2FydC1zaG9wcGluZ29vLWRhdGFic2UtcHVibGljLmM3czRhdWdvNDhwYi5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbTozMzA2L2NhcnRkYj91c2VVbmljb2RlPXRydWUmY2hhcmFjdGVyRW5jb2Rpbmc9dXRmOG1iNA=="
  CART_DB_USERNAME: "c2hvcHBpbmdvb2FkbWlu"
  CART_DB_PASSWORD: "NDA0bm90Zm91bmQh"
  # AI secret 추가
  # YOUTUBE_API_KEY: "QUl6YVN5QVNaRXhFVGdfVVlQSm5tanJTMHZwdzgyaEk4YnFWLW4w"
  # AI_BRAND_DB_HOST: "YnJhbmQtc2hvcHBpbmdvby1kYi1wYi5jN3M0YXVnbzQ4cGIuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20="
  # AI_BRAND_DB_PORT: "MzMwNg=="
  # AI_BRAND_DB_NAME: "YnJhbmRkYg=="
  # AI_BRAND_DB_USER: "c2hvcHBpbmdvb2FkbWlu"
  # AI_BRAND_DB_PASSWORD: "NDA0bm90Zm91bmQh"

  
