apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  DB_URL: {{ .Values.env.secret.DB_URL | b64enc }}
  DB_USERNAME: {{ .Values.env.secret.DB_USERNAME | b64enc }}
  DB_PASSWORD: {{ .Values.env.secret.DB_PASSWORD | b64enc }}