apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  USER_DB_URL: {{ .Values.backend.env.secret.USER_DB_URL | b64enc }}
  USER_DB_USERNAME: {{ .Values.backend.env.secret.USER_DB_USERNAME | b64enc }}
  USER_DB_PASSWORD: {{ .Values.backend.env.secret.USER_DB_PASSWORD | b64enc }}
  BRAND_DB_URL: {{ .Values.backend.env.secret.BRAND_DB_URL | b64enc }}
  BRAND_DB_USERNAME: {{ .Values.backend.env.secret.BRAND_DB_USERNAME | b64enc }}
  BRAND_DB_PASSWORD: {{ .Values.backend.env.secret.BRAND_DB_PASSWORD | b64enc }}
  
