# Backend Services
{{- range .Values.backend.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-svc
  namespace: shortpingoo
spec:
  type: {{ .type | default "ClusterIP" }}
  selector:
    app: {{ .name }}
  ports:
    {{- range .ports }}
    - protocol: TCP
      port: {{ .number }}
      targetPort: {{ .number }}
    {{- end }}
{{- end }}

---
# Frontend Services
apiVersion: v1
kind: Service
metadata:
  name: shortpingoo-frontend-svc
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.port }}
